# Generated by Django 5.2.11 on 2026-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpost',
            name='job_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
