# Generated by Django 5.2.11 on 2026-03-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_application_status_alter_application_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpost',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
